### PR TITLE
pySOT

### PR DESCRIPTION
**Pull request by evayang234**

### CODE REVIEW

**Comment by dme65** [comment]
Hi! What are you trying to commit?

**Comment by evayang234** [comment]
Hi! So sorry but I did it by accident. I was not supposed to and actually did not make any change. Just I found it not deletable once the activity became public after I clicked the “push”. I am really sorry, and hope it didn’t cause you much trouble.

**Comment by dme65** [comment]
No damage done. I'll just go ahead and close the request. 

Cheers,
David

**Comment by evayang234** [comment]
Thanks David!

Sincerely,
Eva

**Pull request closed without merging**
